GET https://crypto.huzhihui.org.cn HTTP/1.1

###

POST    http://127.0.0.1:8000/add_list/ HTTP/1.1
content-type: application/json

{
    "name": "POST",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
###

DELETE http://127.0.0.1:8000/delete_list/ HTTP/1.1
content-type: application/json

{
    "name": "DELETE",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
PUT http://127.0.0.1:8000/update_list/ HTTP/1.1
content-type: application/json

{
    "name": "PUT",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
###
GET  http://127.0.0.1:8000/query_list/ HTTP/1.1
content-type: application/json

{
    "name": "get",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

