# Generated by Django 3.0.5 on 2020-04-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200418_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(max_length=1)),
            ],
        ),
    ]
