# Generated by Django 3.0.5 on 2020-04-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_crypto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='sex',
            field=models.IntegerField(default=1),
        ),
    ]
